title: My Title
author: GitHub User
email: my-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My site description
theme: minima
# social links
twitter_username: my-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  my-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
